#! /bin/bash

###
# Run VMs
# 
# Saul <saul@saulhoward.com>
###

case "$1" in
    "short-name")
        VM_NAME=long-name
        VM_IP=192.168.1.1
        ;;
    *)
        ;; 
esac

VM_START="/home/saul/bin/vm-start"
$VM_START -n $VM_NAME -i $VM_IP

