#! /bin/bash

###
# Start up a Qemu VM
#
#     vm-start -n [VM NAME] -i [IP ADDRESS]
# 
# Saul <saul@saulhoward.com>
###

usage()
{
cat << EOF
usage: $0 options

Start a Qemu VM

OPTIONS:
   -h        Show this message
   -n name   VM name (required)
   -i ip     IP address (required)
   -m mem    Memory (eg, 1024)
   -v        Visual mode
EOF
}

while getopts "hn:i:m:v" opt; do
    case $opt in
        h)
            usage
            exit 1
            ;;
        n)
            VMNAME=$OPTARG
            ;;
        i)
            IPADDRESS=$OPTARG
            ;;
        m)
            MEM=$OPTARG
            ;;
        v)
            VISUALMODE=1
            ;;
        ?)
            usage
            exit
            ;;
    esac
done

if [ -z "$VMNAME" -o -z "$IPADDRESS" ]
then
    echo "VM or IP not set"
    exit
fi

echo "Starting VM $VMNAME"
echo "with IP $IPADDRESS"

MACHINE_DIR='/home/saul/machines/qemu'
USERID=`whoami`

echo "echo 1 > /proc/sys/net/ipv4/conf/wlan0/proxy_arp" | sudo sh
echo "echo 1 > /proc/sys/net/ipv4/conf/eth0/proxy_arp" | sudo sh

# name our tap interface tap{MACHINE}
IFACE=tap$VMNAME
sudo ip tuntap add mode tap user $USERID $IFACE vnet_hdr

echo "echo 1 > /proc/sys/net/ipv4/conf/$IFACE/proxy_arp" | sudo sh
sudo ip link set $IFACE up
sudo route add -host $IPADDRESS dev $IFACE

# This line creates a random mac address. The downside is the dhcp
# server will assign a different ip each time
printf -v macaddr "52:54:%02x:%02x:%02x:%02x" $(( $RANDOM & 0xff)) $(( $RANDOM & 0xff )) $(( $RANDOM & 0xff)) $(( $RANDOM & 0xff ))
# Instead, uncomment and edit this line to set an static mac address.
# The benefit is that the dhcp server will assign the same ip.
#macaddr='52:54:be:36:42:a9'

if [ -n "$MEM" ]
then
    MEMOPT="-m $MEM"
else
    MEMOPT="-m 512"
fi
 
if [ "$VISUALMODE" = 1 ]
then
    VGA="-vga std"
else
    VGA="-vga none -display none -daemonize"
fi
 
qemu-system-x86_64 -netdev type=tap,id=vnet0,ifname="$IFACE" \
    -device virtio-net-pci,netdev=vnet0,id=net0,mac="$macaddr" \
    $MEMOPT -cpu host -smp cores=2 -enable-kvm \
    -drive file=$MACHINE_DIR/$VMNAME.qcow2,if=virtio $VGA
 
# remove the tap iface
sudo ip tuntap del $IFACE mode tap
